spring:
  application:
    name: content-service

  datasource:
    url: #Url
    username: #USERNAME
    password: #PASSWORD

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
      max-request-size: 12MB

  data:
    redis:
      port: 6379
      host: ${SPRING_REDIS_HOST:content-redis}


  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 11115

user:
  service:
    address: ${USER_SERVICE_HOST:user-service}
    port: ${USER_SERVICE_GRPC_PORT:11113}

springdoc:
  swagger-ui:
    config-url: /api/content/v3/api-docs/swagger-config
    url: /api/content/v3/api-docs
    path: /v3/swagger-ui
