server:
  port: 11111

security:
  jwt:
    secret: #key

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - https://thatotakunetwork.netlify.app
              - "http://127.0.0.1:5500"
              - "http://localhost:5500"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      server:
        webflux:
          routes:
            - id: authentication-service-route
              uri: http://host.docker.internal:11112
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

            - id: user-service-api-docs
              uri: http://host.docker.internal:11113
              predicates:
                - Path=/api/profile/v3/**
              filters:
                - StripPrefix=2

            - id: search-service-api-docs
              uri: http://host.docker.internal:11114
              predicates:
                - Path=/api/search/v3/**
              filters:
                - StripPrefix=2

            - id: content-service-api-docs
              uri: http://host.docker.internal:11115
              predicates:
                - Path=/api/content/v3/**
              filters:
                - StripPrefix=2

            - id: recommendation-service-api-docs
              uri: http://host.docker.internal:11116
              predicates:
                - Path=/api/recommendation/v3/**
              filters:
                - StripPrefix=2

            - id: user-service
              uri: http://host.docker.internal:11113
              predicates:
                - Path=/api/profile/**
              filters:
                - StripPrefix=2
                - JwtValidation

            - id: search-service
              uri: http://host.docker.internal:11114
              predicates:
                - Path=/api/search/**
              filters:
                - StripPrefix=2
                - JwtValidation

            - id: content-service
              uri: http://host.docker.internal:11115
              predicates:
                - Path=/api/content/**
              filters:
                - StripPrefix=2
                - JwtValidation

            - id: recommendation-service
              uri: http://host.docker.internal:11116
              predicates:
                - Path=/api/recommendation/**
              filters:
                - StripPrefix=2
                - JwtValidation
